baseURL = 'https://lexp.lt'
languageCode = 'en-us'
title = "Lexynomicon"

theme = 'terminal'
pagination.pagerSize = 10

defaultContentLanguage = 'en'

enableGitInfo = true
enableRobotsTXT = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Lexynomicon"
    [languages.en.params]
      subtitle = ""
      owner = "Lexy Plt"
      keywords = "blog, programming, arkscript, cpp, cplusplus, python, coding, code, teaching, knowledge base"
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "SIGSEV - Page not found..."
      missingBackButtonLabel = "Back to home page"

      [languages.en.params.logo]
        logoText = "Lexynomicon"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
          weight = 1
        [[languages.en.menu.main]]
          identifier = "tags"
          name = "Tags"
          url = "/tags"
          weight = 2
        [[languages.en.menu.main]]
          identifier = "github"
          name = "GitHub"
          url = "https://github.com/SuperFola"
          weight = 3
        [[languages.en.menu.main]]
          identifier = "mastodon"
          name = "Mastodon"
          url = "https://hachyderm.io/@lexplt"
          weight = 4
        [[languages.en.menu.main]]
          identifier = "rss"
          name = "RSS Feed"
          url = "/index.xml"
          weight = 5

[outputs]
  home = ['html', 'rss']

[services]
  [services.rss]
    limit = -1  # unlimited articles

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

