[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/SuperFola"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://hachyderm.io/@lexplt"

[social.params]
icon = "brand-mastodon"

