rssFullContent = true
favicon = "favicon.png"

contentTypeName = "posts"
showMenuItems = 3
fullWidthTheme = false
centerTheme = true
dateFormat = "Jan 02, 2006"
showLastUpdated = true
Toc = true
readingTime = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

